formatter: markdown table

recursive:
  enabled: true
  path: examples
  include-main: true

output:
  file: README.md
  mode: inject
  # template: |-
  #   <!-- BEGIN_TF_DOCS -->
  #   {{ .Content }}
  #   <!-- END_TF_DOCS --> 